# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#Comment

# resources:
#  repositories:
#    - repository: team1
#      type: GitHub
#      endpoint: akshansh04
#      name: akshansh04/Repo1

jobs:
#  - deployment: deploy
#    displayName: somedeploy
#    pool:
#     name: default
#    environment: environment1
#  - job: J1
#    pool:
#     name: default
#    steps:
#       - task: PublishBuildArtifacts@1
#         inputs:
#          PathtoPublish: 'artifact1.1'
#          ArtifactName: 'A1.1'
#          publishLocation: 'Container'
#       - task: PublishBuildArtifacts@1
#         inputs:
#          PathtoPublish: 'artifact1.2'
#          ArtifactName: 'A1.2'
#          publishLocation: 'Container'
#       - powershell: |
#             ls $(Build.ArtifactStagingDirectory)/
 - job: J2
   pool:
    name: Aksriv
   steps:
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: 'artifact2'
         ArtifactName: 'A2'
         publishLocation: 'Container'
